<?php
/**
 * Copyright © Rafeektt. All rights reserved.
 * See LICENCE.txt for licence details.
 */
declare(strict_types=1);

use Rafeektt\MAdminBranding\ViewModel\AdminLogo;

/** @var AdminLogo $viewModel */
$viewModel = $block->getViewModel();
?>

<?php if ($copyrightText = $viewModel->getCopyrightText()): ?>
    <div class="copyright">
        <?= $block->escapeHtml($copyrightText) ?>
    </div>
<?php endif;
